// Generated by wrangler types

interface Env {
  AI: Ai;
  AUDIO_BUCKET: R2Bucket;
  PRESENT_SELF: DurableObjectNamespace;
  FUTURE_SELF: DurableObjectNamespace;
  ELEVENLABS_API_KEY: string;
  ENVIRONMENT: string;
}
