// Generated by wrangler types

interface Env {
  AI: Ai;
  AUDIO_BUCKET: R2Bucket;
  PresentSelfAgent: DurableObjectNamespace;
  FutureSelfAgent: DurableObjectNamespace;
  ELEVENLABS_API_KEY: string;
  ELEVENLABS_AGENT_ID: string;
  ENVIRONMENT: string;
}
